with-expecter: true
inpackage: true
dir: .
packages:
  github.com/ppoonk/shy/core/server:
    interfaces:
      udpIO:
        config:
          mockname: mockUDPIO
      udpEventLogger:
        config:
          mockname: mockUDPEventLogger
      UDPConn:
        config:
          mockname: mockUDPConn
