with-expecter: true
inpackage: true
dir: .
packages:
  github.com/ppoonk/shy/extras/outbounds:
    interfaces:
      PluggableOutbound:
        config:
          mockname: mockPluggableOutbound
      UDPConn:
        config:
          mockname: mockUDPConn
